# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mPhone', models.CharField(max_length=20)),
                ('userType', models.CharField(choices=[('TR', 'Teacher'), ('SD', 'Student')], default='SD', max_length=2)),
            ],
            options={
                'ordering': ('ID',),
            },
        ),
    ]
