# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_auto_20180321_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.FileField(upload_to=upload.models.lessonsPath)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='experimenter', to='users.UserInfo')),
            ],
        ),
    ]
